
% ======================================================================= %
%                                                                         %
% This script produces Figure 1 in our paper, a global map of the         %
% locations of all known historical ship-based time-series research       %
% programs that have measured POC flux repeatedly over time in locations  %
% with deep bathymetry (>1000 m). The figure is finished on PPT. The      %
% script has 3 sections:                                                  %
%   Section 1 - Presets.                                                  %
%   Section 2 - Load Longhurst provinces.                                 %
%   Section 3 - Plot Figure 1.                                            %
%                                                                         %
%   WRITTEN BY A. RUFAS, UNIVERISTY OF OXFORD                             %
%   Anna.RufasBlanco@earth.ox.ac.uk                                       %
%                                                                         %
%   Version 1.0 - Completed 7 April 2024                                  %
%                                                                         %
% ======================================================================= %

close all; clear all; clc
addpath(genpath('./data/raw/'));
addpath(genpath('./data/processed/'));
addpath(genpath('./code/'));
addpath(genpath('./resources/external/'));
addpath(genpath('./resources/internal/'));

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 1 - DISPLAY STATION NAMES, THEIR STATUS AND LOCATION
% -------------------------------------------------------------------------

labelStations = {...
    'HAUSGARTEN',...
    'DYFAMED',...
    'CIS',...
    'L1/K276',...
    'BATS/OFP',...
    'ESTOC',...
    'CB',...
    'CVOO',...
    'CARIACO',...
    'South Georgia',...
    'Palmer',...
    'OSP',...
    'K2',...
    'S1',...
    'KNOT',...
    'M',...
    'HOT',...
    'SEATS',...
    'EqPac',...
    'CQ',...
    'CC',...
    'AST',...
    'BBT',...
    'SOTS',...
    'KERFIX',...
    'L2',...
    'L3',...
    'WR/WBST-W',...
    'PAP-SO'};

operationalStatus = ['g','r','g','g','g','r','g','g','r','r','g','r',...
    'g','g','r','g','g','g','r','r','r','g','g','g','r','r','r','r','g'];

% List of latitudes
Ybb = [...
  79.0,...
  43.25,...
  59.3,... % CIS
  33,...
  31.4,...
  29.2,... % ESTOC
  21,...
  17.9,...
  10.5,... % CARIACO
  -55,...
  -64.7,... % Palmer
  50,...
  47,... % K2
  30,... % S1
  44,...
  34.50,...
  22.45,...
  18,...
  0,... % EqPac
  -30,...
  -36,...
  15,...
  13,...
  -47,... % SOTS
  -50.4,...
  47,...
  54,...
  -21.5,... % 20ºS for WR and 23ºS for WBST-W
  49]; 

% List of longitudes (-180 to 180ºE) (substract 360º to convert to 0 to 360ºE)
Xbb = [ 
    4.0,...
    7.52,...
    -39.5,... % CIS
    -22,...
    -64.1,...
    -15.5,... % ESTOC
    -19.5,...
    -24.3,...
    -64.66,... % CARIACO
    -40.5,...
    -64.0,... % Palmer
    -145,...
    160 - 360,... % K2
    145 - 360,... % S1
    155 - 360,... % KNOT
    -123,...
    -158,...
    118 - 360,... % SEATS
    -140,...
    -73.11,...
    -74.49,...
    65,...
    85,...
    142 - 360,... % SOTS
    68.25,...
    -20,...
    -21,...
    10.5,... % 9ºE for WR and 12ºE for WBST-W
    -16.5]; 

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 2 - LOAD LONGHURST PROVINCES
% -------------------------------------------------------------------------

shapefileLonghurst = 'Longhurst_world_v4_2010';
longhurstProvinces = m_shaperead(shapefileLonghurst); % lat/lon coordinates

% =========================================================================
%%
% -------------------------------------------------------------------------
% SECTION 3 - PLOT FIGURE 1A
% -------------------------------------------------------------------------

colourScale = brewermap(4,'*Blues');

figure()
m_proj('robinson','lat',[-90 90],'clongitude',-70); 

for iProv = 1:length(longhurstProvinces.ncst) 
    x = longhurstProvinces.ncst{iProv}(:,1); 
    y = longhurstProvinces.ncst{iProv}(:,2); 
    idx = find(isnan(x)); % find positions of NaNs 
    idx = [1 idx' length(x)]; % append first and last position 
    for i = 1:length(idx)-1
        pos = idx(i):idx(i+1); % get the required position 
        xi = x(pos) ; yi = y(pos); % get the coordinates 
        % Remove NaN's to fill polygons with colour
        xi(isnan(xi)) = [];
        yi(isnan(yi)) = [];
        % Polar
        if (iProv == 1 || iProv >= 53) 
            m_patch(xi,yi,colourScale(1,:),'EdgeColor',[0.3, 0.3, 0.3]);
        % Subpolar
        elseif (iProv == 2 || iProv == 3 || iProv == 4 || iProv == 30 ||... 
            iProv == 31 || iProv == 32 || iProv == 34 || iProv == 36 ||...
            iProv == 51 ||iProv == 52) 
            m_patch(xi,yi,colourScale(2,:),'EdgeColor',[0.3, 0.3, 0.3]); 
        % Subtropical
        elseif (iProv == 5 || iProv == 6 || iProv == 10 || iProv == 18 ||...
            iProv == 23 || iProv == 35 || iProv == 37 || iProv == 38 ||... 
            iProv == 41 || iProv == 42)  
            m_patch(xi,yi,colourScale(3,:),'EdgeColor',[0.3, 0.3, 0.3]); 
        % Equatorial
        elseif (iProv == 7 || iProv == 8 || iProv == 9 || iProv == 22 ||... 
            iProv == 39 || iProv == 40) 
            m_patch(xi,yi,colourScale(4,:),'EdgeColor',[0.3, 0.3, 0.3]); 
        % The rest
        else
            m_patch(xi,yi,'w','EdgeColor',[0.3, 0.3, 0.3]); 
        end
%         alpha(0.5)
    end
    hold on
end
hold on

m_coast('patch',[0.8 0.8 0.8],'edgecolor',[0.8 0.8 0.8]);
hold on
m_grid('tickdir','out','linewi',2,'gridcolor','w','linestyle','-');
hold on

for i = 1:length(Ybb)
    if (operationalStatus(i) == 'r')
        fillcolor = [1 0 0];
    elseif (operationalStatus(i) == 'g')
        fillcolor = [0 1 0];
    end
    if (i == 1)
        h1 = m_scatter(Xbb(i),Ybb(i),70,fillcolor,'filled','MarkerEdgeColor','k');
    elseif (i == 2)
        h2 = m_scatter(Xbb(i),Ybb(i),70,fillcolor,'filled','MarkerEdgeColor','k');
    else
        m_scatter(Xbb(i),Ybb(i),70,fillcolor,'filled','MarkerEdgeColor','k','HandleVisibility','off');
    end
    hold on;
end
hold on;

% % Add time-series sites
% for i = 1:length(labelStations)
%     [~,ln,lt]=m_lldist([-123-6/60 Xbb(i)],[49+13/60 Ybb(i)],40); 
%     m_text(ln(end),lt(end),sprintf('%s',labelStations{i}));
%     hold on
% end

% Add legend
lg = legend([h1(1),h2(1)],'Operational','Discontinued');
lg.Position(1) = 0.43; lg.Position(2) = 0.07;
lg.Orientation = 'horizontal';
lg.ItemTokenSize = [25,10];
lg.FontSize = 13;
lg.Box = 'off';

% Save
%set(gcf,'PaperPositionMode','auto')
%print(gcf,fullfile('figures/','map_timeseries_stations'),'-dpdf','-r600') % for editing with Illustrator
exportgraphics(gcf,fullfile('figures/','map_timeseries_stations.png'),'Resolution',600)

